export const SUBSCRIBE_LOGIN_STATE = 'auth/SUBSCRIBE_LOGIN_STATE';
export const UNSUBSCRIBE_LOGIN_STATE = 'auth/UNSUBSCRIBE_LOGIN_STATE';
export const RECEIVED_LOGIN_STATE = 'auth/RECEIVED_LOGIN_STATE';