# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'

target 'ReactNativeAuthApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeAuthApp

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../mods/lottie-react-native.podspec'

  target 'ReactNativeAuthAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
