# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'

target 'ReactNativeAuthApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeAuthApp
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'ReactNativeAuthAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
